server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product
    platform: postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
      database-platform: PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER